[package]
name = "cargo-jdi"
version = "0.1.2"
authors = ["Srikanth Suresh <4140019+srikwit@users.noreply.github.com>"]
edition = "2018"
description = "A tool to help developers fight with the Rust compiler"
license = "MIT"

[dependencies]
rand = "*"
